/*** Equipe: 
/*** Karoline Lima ***/
/*** Maria Janaina ***/
/**  Yane Lisset   ***/

/** criaçao do banco de dados ***/
CREATE DATABASE CONTROLE
USE CONTROLE
GO
/*** criaçao da tabela função ***/
CREATE TABLE FUNCAO
(
    IDFUNCAO VARCHAR(3) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    SALARIO SMALLMONEY NOT NULL,
    CONSTRAINT PK_FUNCAO PRIMARY KEY (IDFUNCAO),
    CONSTRAINT AK_FUNCAO_SAL UNIQUE (SALARIO)
)
/*** criaçao da tabela funcionario ***/
CREATE TABLE FUNCIONARIO 
(   
    IDFUNCIONARIO VARCHAR(3) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    RUA VARCHAR(30) NULL,
    NUMERO VARCHAR(10) NULL,
    BAIRRO VARCHAR (30) NULL,
    IDFUNCAO VARCHAR(3) NOT NULL,
    SEXO VARCHAR (1) NULL,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (IDFUNCIONARIO),
    CONSTRAINT FK_FUNCIONARIO_FUNCAO FOREIGN KEY (IDFUNCAO) REFERENCES FUNCAO,
    CONSTRAINT AK_FUNCIONARIO_NOME UNIQUE (NOME),
    CONSTRAINT CK_FUNCIONARIO_SEXO CHECK (UPPER(SEXO) IN ('F', 'M'))
)
/*** criaçao da tabela chefia ***/
CREATE TABLE CHEFIA
(
    IDFUNCIONARIOCHEFIA VARCHAR(3) NOT NULL,
    IDFUNCIONARIOCHEFIADO VARCHAR(3) NOT NULL,
    CONSTRAINT FK_CHEFIA_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIOCHEFIA) REFERENCES FUNCIONARIO,
    CONSTRAINT FK_CHEFIADO_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIOCHEFIADO) REFERENCES FUNCIONARIO,
    CONSTRAINT PK_CHEFIA PRIMARY KEY (IDFUNCIONARIOCHEFIA, IDFUNCIONARIOCHEFIADO)
)
/*** criaçao da tabela dependente ***/
CREATE TABLE DEPENDENTE 
(
    IDDEPENDENTE VARCHAR(3) NOT NULL,
    IDFUNCIONARIO VARCHAR(3) NOT NULL,
    NOME VARCHAR (30) NOT NULL,
    IDADE VARCHAR(2) NOT NULL,
    CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO,
    CONSTRAINT PK_DEPENDENTE PRIMARY KEY (IDDEPENDENTE, IDFUNCIONARIO),
    CONSTRAINT AK_DEPENDENTE_NOME UNIQUE (NOME),
    CONSTRAINT CK_DEPENDENTE CHECK (IDADE BETWEEN 0 AND 18)

)
/*** criaçao da tabela cartao ***/
CREATE TABLE CARTAO 
(
    CODCARTAO VARCHAR(3) NOT NULL,
    VENCIMENTO DATE NOT NULL,
    PONTUACAO INT DEFAULT (0),
    CONSTRAINT PK_CARTAO PRIMARY KEY (CODCARTAO)
)
/*** criacao da tabela cliente ***/
CREATE TABLE CLIENTE 
(
    CODCLIENTE VARCHAR(3) NOT NULL, 
    NOME VARCHAR(30) NOT NULL,
    CODCARTAO VARCHAR(3) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLIENTE),
    CONSTRAINT AK_CLIENTE_NOME UNIQUE (NOME),
    CONSTRAINT FK_CLIENTE_CARTAO FOREIGN KEY (CODCARTAO) REFERENCES CARTAO,
    CONSTRAINT AK_CLIENTE_CARTAO UNIQUE (CODCARTAO)
)
/*** criaçao da tabela fone ***/
CREATE TABLE FONE 
(
    CODCLIENTE VARCHAR(3) NOT NULL, 
    NUMERO VARCHAR(15) NOT NULL,
    CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE,
    CONSTRAINT PK_FONE PRIMARY KEY (CODCLIENTE, NUMERO)
)
/*** criaçao da tabela estoque ***/
CREATE TABLE ESTOQUE 
(
    IDESTOQUE VARCHAR(3) NOT NULL, 
    CAPACIDADEMAX VARCHAR(30) NOT NULL,
    TEMPERATURA VARCHAR(30) DEFAULT ('AMBIENTE'),
    CONSTRAINT PK_ESTOQUE PRIMARY KEY (IDESTOQUE)
)
/*** criaçao da tabela produto ***/
CREATE TABLE PRODUTO 
(
    CODPRODUTO VARCHAR(3) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL, 
    VALOR_UNITARIO SMALLMONEY NOT NULL,
    IDESTOQUE VARCHAR(3) NOT NULL,
    QUANTIDADE INT DEFAULT (0),
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODPRODUTO),
    CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY (IDESTOQUE) REFERENCES ESTOQUE,
    CONSTRAINT AK_PRODUTO_DESC UNIQUE (DESCRICAO)
)

/*** criaçao da tabela pedido ***/
CREATE TABLE PEDIDO
(
    CODPEDIDO VARCHAR(3) NOT NULL,
    VALOR_TOTAL SMALLMONEY NOT NULL,
    IDFUNCIONARIO VARCHAR(3) NOT NULL,
    CODPRODUTO VARCHAR(3) NOT NULL,
    CODCLIENTE VARCHAR(3) NOT NULL, 
    CONSTRAINT PK_PEDIDO PRIMARY KEY (CODPEDIDO),
    CONSTRAINT FK_PEDIDO_FUNCIONARIO FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO,
    CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO, 
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE

)
/*** criaçao da tabela transporte ***/
CREATE TABLE TRANSPORTE 
(
    PLACA VARCHAR(7) NOT NULL,
    CAPACIDADE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TRANSPORTE PRIMARY KEY (PLACA)
)
/*** criaçao da tabela doaçao ***/
CREATE TABLE DOACAO 
(
    NUMDOACAO VARCHAR(3) NOT NULL,
    VALOR SMALLMONEY NOT NULL,
    DESTINO VARCHAR(20) DEFAULT ('Lar dos idosos')
    CONSTRAINT PK_DOACAO PRIMARY KEY (NUMDOACAO)
)

/*** criaçao da tabela referente ao ternário ***/
CREATE TABLE PDC 
(
    CODCLIENTE VARCHAR(3) NOT NULL, 
    CODPEDIDO VARCHAR(3) NOT NULL, 
    NUMDOACAO VARCHAR(3) NOT NULL,
    CONSTRAINT FK_PDC_CLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE,
    CONSTRAINT FK_PDC_PEDIDO FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
    CONSTRAINT FK_PDC_DOACAO FOREIGN KEY (NUMDOACAO) REFERENCES DOACAO,
    CONSTRAINT PK_PDC PRIMARY KEY (CODCLIENTE, CODPEDIDO, NUMDOACAO)
)
/*** criacao da tabela referente a entidade associativa ***/
CREATE TABLE PPT 
(
    PLACA VARCHAR(7) NOT NULL, 
    CODPEDIDO VARCHAR(3) NOT NULL, 
    CODPRODUTO VARCHAR(3) NOT NULL,
    CONSTRAINT FK_PPT_TRANSPORTE FOREIGN KEY (PLACA) REFERENCES TRANSPORTE,
    CONSTRAINT FK_PPT_PEDIDO FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
    CONSTRAINT FK_PPT_PRODUTO FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTO,
    CONSTRAINT PK_PPT PRIMARY KEY (PLACA, CODPEDIDO)
)
